### ISSUE TITLE
This is awesome

### ISSUE THREAD

**Issue by nicola** [VictorBjelkholm/ipfscrape#2]
This is incredible, I was implementing this yesterday night, but I was undecided how far I should have scraped and how to prove that the content was actually the content online (since you could fake links, right)

But you actually started it, I will try to hang aroung here

Good work!

**Comment by victorb** [comment]
Good points. This currently only scrapes the immediate page and the assets needed to render the page. Might add in the future to go down some customization levels. wget supports that out of the box so should be easy to add.

Regarding proving the content was actually the content online. It's a thing I didn't really thought about. Have any more thoughts around that?

And, thanks for the feedback, always appreciate it :)

**Comment by davidar** [comment]
> Regarding proving the content was actually the content online. It's a thing I didn't really thought about. Have any more thoughts around that?

I've thought about it, but unfortunately there doesn't seem to be a good solution. In _principle_ websites could sign content using their SSL key, but in practice things don't work that way.
